FROM node:22-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY web/package.json web/package-lock.json ./

RUN npm ci

COPY web/ ./

RUN npm run build

ENV NODE_ENV=production
ENV PORT=8096
ENV HOSTNAME=0.0.0.0

EXPOSE 8096

CMD ["npm", "start"]
